language: cpp
compiler:
- clang
- gcc

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libmysqlclient-dev
    - cd "${TRAVIS_BUILD_DIR}"

script: "cd flamingoserver && cmake . && make"

branches:
    only:
      - master

after_success:
    - bash <(curl -s https://codecov.io/bash)
